name: Telegram Bot

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'  # Har 5 soatda qayta ishga tushadi

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 5 soat

    steps:
      - uses: actions/checkout@v4

      - name: Python o'rnatish
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Kutubxonalarni o'rnatish
        run: pip install python-telegram-bot Pillow img2pdf

      - name: Botni ishga tushirish
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
        run: python bot.py
